/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-29 13:49:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import it.TugurioSemplice.*;
import DataManagement.*;
import it.TugurioSemplice.Admin.*;
import java.util.*;
import it.TugurioSemplice.*;
import DataManagement.*;
import it.TugurioSemplice.Admin.*;

public final class _404_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1745829789000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("DataManagement");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("it.TugurioSemplice");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("it.TugurioSemplice.Admin");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"it\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/error.css\">\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <title>Errore 404 - Pagina non trovata</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <img src=\"photo/logo.png\" alt=\"logo\" class=\"logo\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <img src=\"photo/404.jpg\" alt=\"Immagine di errore 404\" class=\"error-image\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <center><b>Errore 404</b></center>\r\n");
      out.write("        <br>\r\n");
      out.write("        Ci dispiace, la pagina che stai cercando non è stata trovata.\r\n");
      out.write("        <br><br>\r\n");
      out.write("         <a class=\"button\" href=\"index.jsp\" >Torna alla homepage</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footer.css\">\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <title>TugurioSemplice - Home</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("       <footer class=\"footer-container\">\n");
      out.write("    <div class=\"footer-links\">\n");
      out.write("        <a href=\"about.jsp\" title=\"Informazioni su di noi\">Chi siamo</a>\n");
      out.write("        <a href=\"privacy.jsp\" title=\"La nostra politica sulla privacy\">Privacy Policy</a>\n");
      out.write("        <a href=\"terms.jsp\" title=\"Termini del servizio\">Termini e Condizioni</a>\n");
      out.write("        <a href=\"contact.jsp\" title=\"Contattaci\">Contatti</a>\n");
      out.write("    </div>\n");
      out.write("    <p class=\"text copyright\">&copy; 2025 TugurioSemplice. Tutti i diritti riservati.</p>\n");
      out.write("</footer>\n");
      out.write("    </body>\n");
      out.write("</html>");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
