/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-29 13:59:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import it.TugurioSemplice.*;
import DataManagement.*;
import it.TugurioSemplice.Admin.*;

public final class Fattura_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("DataManagement");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("it.TugurioSemplice");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("it.TugurioSemplice.Admin");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

// Recupera l'ID dall'URL
int idOrdine = Integer.parseInt(request.getParameter("idOrdine"));

// Recupera l'utente dalla sessione
ClienteBean utente = (ClienteBean) session.getAttribute("user");

// Recupera l'ordine e i dettagli dal database
OrdineDAO ordineDAO = new OrdineDAO();
OrdineBean ordine = ordineDAO.doRetrieveByKey(idOrdine);
ArrayList<Map<String, Object>> dettagliOrdine = ordineDAO.getDettagliOrdine(idOrdine);

// Recupera pagamento e spedizione se esistono
PagamentoBean pagamento = ordineDAO.retrievePayment(idOrdine);
SpedizioneBean spedizione = ordineDAO.retrieveShipping(idOrdine);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <title>Fattura</title>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    ");

    if(utente != null && ordine != null) 
    {
    
      out.write("\n");
      out.write("      <div>\n");
      out.write("        <h1>FATTURA</h1>\n");
      out.write("        <p>Numero Fattura: FAT-");
      out.print( ordine.getIdOrdine() );
      out.write("</p>\n");
      out.write("        <p>Data: ");
      out.print( ordine.getDataOrdine() );
      out.write("</p>\n");
      out.write("        \n");
      out.write("        <h2>Venditore</h2>\n");
      out.write("        <p>Tugurio Semplice S.r.l.</p>\n");
      out.write("        <p>Via Esempio, 123</p>\n");
      out.write("        <p>00123 Roma (RM)</p>\n");
      out.write("        <p>P.IVA: 12345678901</p>\n");
      out.write("        \n");
      out.write("        <h2>Cliente</h2>\n");
      out.write("        <p>Nome: ");
      out.print( utente.getAnagrafia() != null ? utente.getAnagrafia().getNome() + " " + utente.getAnagrafia().getCognome() : "N/D" );
      out.write("</p>\n");
      out.write("        <p>Codice Fiscale: ");
      out.print( utente.getAnagrafia() != null ? utente.getAnagrafia().getCf() : "N/D" );
      out.write("</p>\n");
      out.write("        ");
 if(utente.getIndirizzoSpedizione() != null) { 
      out.write("\n");
      out.write("          <p>Indirizzo: ");
      out.print( utente.getIndirizzoSpedizione().getVia() );
      out.write("</p>\n");
      out.write("          <p>Città: ");
      out.print( utente.getIndirizzoSpedizione().getCitta() );
      out.write(' ');
      out.write('(');
      out.print( utente.getIndirizzoSpedizione().getProvincia() );
      out.write(")</p>\n");
      out.write("          <p>CAP: ");
      out.print( utente.getIndirizzoSpedizione().getCap() );
      out.write("</p>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("          <p>Indirizzo: N/D</p>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        \n");
      out.write("        <h2>Dettagli Ordine</h2>\n");
      out.write("        <table border=\"1\">\n");
      out.write("            <tr>\n");
      out.write("                <th>Articolo</th>\n");
      out.write("                <th>Quantità</th>\n");
      out.write("                <th>Prezzo Unitario</th>\n");
      out.write("                <th>Totale</th>\n");
      out.write("            </tr>\n");
      out.write("            ");

            double subtotale = 0;
            if(dettagliOrdine != null && !dettagliOrdine.isEmpty()) {
                for(Map<String, Object> dettaglio : dettagliOrdine) {
                    String nomeProdotto = (String) dettaglio.get("nomeProdotto");
                    int quantita = (Integer) dettaglio.get("quantita");
                    double prezzo = (Double) dettaglio.get("prezzo");
                    double totaleRiga = quantita * prezzo;
                    subtotale += totaleRiga;
            
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td>");
      out.print( nomeProdotto );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( quantita );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( String.format("%.2f", prezzo) );
      out.write(" €</td>\n");
      out.write("                    <td>");
      out.print( String.format("%.2f", totaleRiga) );
      out.write(" €</td>\n");
      out.write("                </tr>\n");
      out.write("            ");
 
                }
            }
            
      out.write("\n");
      out.write("        </table>\n");
      out.write("        \n");
      out.write("        <!-- Sezione pagamento -->\n");
      out.write("        ");
 if(pagamento != null) { 
      out.write("\n");
      out.write("        <h2>Metodo di Pagamento</h2>\n");
      out.write("        <p>Metodo: ");
      out.print( pagamento.getMetodo() );
      out.write("</p>\n");
      out.write("        <p>Importo: ");
      out.print( String.format("%.2f", pagamento.getImporto()) );
      out.write(" €</p>\n");
      out.write("        <p>Data Pagamento: ");
      out.print( pagamento.getDataPagamento() );
      out.write("</p>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        \n");
      out.write("        <!-- Sezione spedizione -->\n");
      out.write("        ");
 if(spedizione != null) { 
      out.write("\n");
      out.write("        <h2>Spedizione</h2>\n");
      out.write("        <p>Metodo: ");
      out.print( spedizione.getMetodo() );
      out.write("</p>\n");
      out.write("        <p>Spese: ");
      out.print( String.format("%.2f", spedizione.getSpese()) );
      out.write(" €</p>\n");
      out.write("        <p>Data Consegna Prevista: ");
      out.print( spedizione.getDataConsegna() );
      out.write("</p>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        <BR>\n");
      out.write("        <p>Fattura emessa elettronicamente</p>\n");
      out.write("        <p>Documento non valido ai fini fiscali</p>\n");
      out.write("        \n");
      out.write("        <div>\n");
      out.write("          <button onclick=\"window.print()\">Stampa Fattura</button>\n");
      out.write("          <a href=\"ProfiloUtente.jsp\">Torna al profilo</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    ");

    } else {
    
      out.write("\n");
      out.write("      <div>\n");
      out.write("        <p>Impossibile generare la fattura. Dati mancanti o utente non autenticato.</p>\n");
      out.write("        <a href=\"index.jsp\">Torna alla Home</a>\n");
      out.write("      </div>\n");
      out.write("    ");

    }
    
      out.write("\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
