/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-29 14:47:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import it.TugurioSemplice.*;
import DataManagement.*;
import it.TugurioSemplice.Admin.*;
import java.util.*;
import it.TugurioSemplice.*;
import DataManagement.*;
import it.TugurioSemplice.Admin.*;
import java.util.*;
import it.TugurioSemplice.*;
import DataManagement.*;
import it.TugurioSemplice.Admin.*;

public final class ProductDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1745829789000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1745829805000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("DataManagement");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("it.TugurioSemplice");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("it.TugurioSemplice.Admin");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

	ProdottoBean product = (ProdottoBean) request.getAttribute("product");
	if(product == null) {
		response.sendRedirect("./product");
		return;
	}
	
	String error = (String)request.getAttribute("error");
	if(error != null) {
		out.println("<div class=\"error-message\">" + error + "</div>");
	}

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("	<head>\n");
      out.write("		<meta charset=\"UTF-8\">\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("		<title>TugurioSemplice - ");
      out.print( product.getNome() );
      out.write("</title>\n");
      out.write("		<style>\n");
      out.write("			.product-container {\n");
      out.write("				display: flex;\n");
      out.write("				flex-wrap: wrap;\n");
      out.write("				max-width: 1200px;\n");
      out.write("				margin: 0 auto;\n");
      out.write("				padding: 20px;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.product-image {\n");
      out.write("				flex: 1;\n");
      out.write("				min-width: 300px;\n");
      out.write("				text-align: center;\n");
      out.write("				padding: 20px;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.product-image img {\n");
      out.write("				max-width: 100%;\n");
      out.write("				height: auto;\n");
      out.write("				border-radius: 8px;\n");
      out.write("				box-shadow: 0 4px 8px rgba(0,0,0,0.1);\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.product-info {\n");
      out.write("				flex: 1;\n");
      out.write("				min-width: 300px;\n");
      out.write("				padding: 20px;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.product-title {\n");
      out.write("				font-size: 24px;\n");
      out.write("				font-weight: bold;\n");
      out.write("				margin-bottom: 10px;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.product-price {\n");
      out.write("				font-size: 22px;\n");
      out.write("				font-weight: bold;\n");
      out.write("				color: #333;\n");
      out.write("				margin: 15px 0;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.product-description {\n");
      out.write("				margin: 20px 0;\n");
      out.write("				line-height: 1.6;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.product-availability {\n");
      out.write("				font-weight: bold;\n");
      out.write("				margin: 10px 0;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.available {\n");
      out.write("				color: green;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.not-available {\n");
      out.write("				color: red;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.quantity-selector {\n");
      out.write("				margin: 20px 0;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.quantity-selector input {\n");
      out.write("				width: 60px;\n");
      out.write("				text-align: center;\n");
      out.write("				padding: 8px;\n");
      out.write("				margin: 0 10px;\n");
      out.write("				border: 1px solid #ddd;\n");
      out.write("				border-radius: 4px;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.add-to-cart {\n");
      out.write("				background-color: #8d847a;\n");
      out.write("				color: white;\n");
      out.write("				border: none;\n");
      out.write("				padding: 12px 24px;\n");
      out.write("				font-size: 16px;\n");
      out.write("				border-radius: 4px;\n");
      out.write("				cursor: pointer;\n");
      out.write("				margin-top: 20px;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.add-to-cart:hover {\n");
      out.write("				background-color: #333;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.add-to-cart:disabled {\n");
      out.write("				background-color: #cccccc;\n");
      out.write("				cursor: not-allowed;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.product-details {\n");
      out.write("				margin-top: 40px;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.product-details h3 {\n");
      out.write("				border-bottom: 1px solid #ddd;\n");
      out.write("				padding-bottom: 10px;\n");
      out.write("				margin-bottom: 20px;\n");
      out.write("			}\n");
      out.write("		</style>\n");
      out.write("	</head>\n");
      out.write("	<body>\n");
      out.write("		");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/header.css\">\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <title>TugurioSemplice - Home</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <header class=\"menu\">\n");
      out.write("            <div class=\"top-bar\">\n");
      out.write("                <span class=\"logo-text\">TUGURIOSEMPLICE</span>\n");
      out.write("                <a class=\"logo-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/logo.png\" width=\"25%\" alt=\"TugurioSemplice Logo\"></a>\n");
      out.write("                ");

                	ClienteBean utente = (ClienteBean) session.getAttribute("user");
                	if(utente != null) { 
                
      out.write("\n");
      out.write("                <a class=\"login-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AreaUtente.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/access.png\" width=\"15%\" alt=\"login\"></a>\n");
      out.write("                ");
 
                } else {
                
      out.write("\n");
      out.write("                <a class=\"login-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AuthSites/Login.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/access.png\" width=\"15%\" alt=\"login\"></a>\n");
      out.write("                ");

                } 
                
      out.write("\n");
      out.write("                <a class=\"cart-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/cart.png\" width=\"15%\" alt=\"carrello\"></a>\n");
      out.write("            </div>  \n");
      out.write("            <div class=\"line\">   \n");
      out.write("                <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("index.jsp") ? "active" : "" );
      out.write("\" href=\"index.jsp\">HOME</a>\n");
      out.write("                <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("about.jsp") ? "active" : "" );
      out.write("\" href=\"about.jsp\">CHI SIAMO</a>\n");
      out.write("                <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("ProductView.jsp") ? "active" : "" );
      out.write("\" href=\"ProductView.jsp\">CATALOGO</a>\n");
      out.write("                <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("contact.jsp") ? "active" : "" );
      out.write("\" href=\"contact.jsp\">CONTATTI</a>  \n");
      out.write("            </div>\n");
      out.write("        </header>    \n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("		\n");
      out.write("		<div class=\"product-container\">\n");
      out.write("			<div class=\"product-image\">\n");
      out.write("				<img src=\"");
      out.print( product.getImmagine() );
      out.write("\" alt=\"");
      out.print( product.getNome() );
      out.write("\" onerror=\"this.src='photo/placeholder.jpg'; this.onerror=null;\">\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<div class=\"product-info\">\n");
      out.write("				<h1 class=\"product-title\">");
      out.print( product.getNome() );
      out.write("</h1>\n");
      out.write("				\n");
      out.write("				<div class=\"product-price\">\n");
      out.write("					€");
      out.print( String.format("%.2f", product.getPrezzoBase()) );
      out.write("\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"product-availability\">\n");
      out.write("					<span class=\"");
      out.print( (product.getQuantita() > 0 && product.getDisponibilita()) ? "available" : "not-available" );
      out.write("\">\n");
      out.write("						");
      out.print( (product.getQuantita() > 0 && product.getDisponibilita()) ? "Disponibile" : "Non disponibile" );
      out.write("\n");
      out.write("					</span>\n");
      out.write("					");
 if(product.getQuantita() > 0 && product.getDisponibilita()) { 
      out.write("\n");
      out.write("						<span> - ");
      out.print( product.getQuantita() );
      out.write(" in magazzino</span>\n");
      out.write("					");
 } 
      out.write("\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"product-description\">\n");
      out.write("					");
      out.print( product.getDescrizione() );
      out.write("\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<form action=\"CartController\" method=\"post\">\n");
      out.write("					<input type=\"hidden\" name=\"action\" value=\"addC\">\n");
      out.write("					<input type=\"hidden\" name=\"id\" value=\"");
      out.print( product.getIdProdotto() );
      out.write("\">\n");
      out.write("					\n");
      out.write("					<div class=\"quantity-selector\">\n");
      out.write("						<label for=\"quantity\">Quantità:</label>\n");
      out.write("						<input type=\"number\" id=\"quantity\" name=\"quantity\" value=\"1\" min=\"1\" max=\"");
      out.print( product.getQuantita() );
      out.write('"');
      out.write(' ');
      out.print( (product.getQuantita() > 0 && product.getDisponibilita()) ? "" : "disabled" );
      out.write(">\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("					<button class=\"add-to-cart\" type=\"submit\" ");
      out.print( (product.getQuantita() > 0 && product.getDisponibilita()) ? "" : "disabled" );
      out.write(">\n");
      out.write("						Aggiungi al Carrello\n");
      out.write("					</button>\n");
      out.write("				</form>\n");
      out.write("				\n");
      out.write("				<div class=\"product-details\">\n");
      out.write("					<h3>Dettagli prodotto</h3>\n");
      out.write("					<p>IVA: ");
      out.print( product.getIva() );
      out.write("%</p>\n");
      out.write("					<p>Codice prodotto: ");
      out.print( product.getIdProdotto() );
      out.write("</p>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footer.css\">\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <title>TugurioSemplice - Home</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("       <footer class=\"footer-container\">\n");
      out.write("    <div class=\"footer-links\">\n");
      out.write("        <a href=\"about.jsp\" title=\"Informazioni su di noi\">Chi siamo</a>\n");
      out.write("        <a href=\"privacy.jsp\" title=\"La nostra politica sulla privacy\">Privacy Policy</a>\n");
      out.write("        <a href=\"terms.jsp\" title=\"Termini del servizio\">Termini e Condizioni</a>\n");
      out.write("        <a href=\"contact.jsp\" title=\"Contattaci\">Contatti</a>\n");
      out.write("    </div>\n");
      out.write("    <p class=\"text copyright\">&copy; 2025 TugurioSemplice. Tutti i diritti riservati.</p>\n");
      out.write("</footer>\n");
      out.write("    </body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("	</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
